FPS = 30
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
REVEAL_SPEED = 8
BOX_SIZE = 40
GAP_SIZE = 10
BOARD_WIDTH = 10
BOARD_HEIGHT = 7

X_MARGIN = int((WINDOW_WIDTH
                - (BOARD_WIDTH * (BOX_SIZE + GAP_SIZE))
                ) / 2)
Y_MARGIN = int((WINDOW_HEIGHT
                - (WINDOW_HEIGHT * (BOX_SIZE + GAP_SIZE))
                ) / 2)

# colors
GRAY = (100, 100, 100)
NAVYBLUE = (60, 60, 100)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
GREEN = (0, 0, 255)
BLUE = (0, 255, 0)
ORANGE = (255, 128, 0)
PURPLE = (255, 0, 255)
CYAN = (0, 255, 255)

BG_COLOR = NAVYBLUE
LIGHT_BG_COLOR = GRAY
BOX_COLOR = WHITE
HIGHLIGHT_COLOR = BLUE

DONNUT = 'donut'
SQUARE = 'square'
DIAMOND = 'diamond'
LINES = 'lines'
OVAL = 'oval'

ALL_COLORS = (GRAY, NAVYBLUE, WHITE, RED, YELLOW, GREEN, BLUE, ORANGE, PURPLE, CYAN)
ALL_SHAPES = (DONNUT, SQUARE, DIAMOND, LINES, OVAL)
